spring.application.name=flight-service
server.port=7172

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/flight_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



# Logging
logging.level.com.project.flightservice=DEBUG

# JWT Secret (must match Auth Service)
jwt.secret=${JWT_SECRET}
