spring.application.name=booking-service
server.port=7173

# ==========================================
# Feign Client Configuration
# ==========================================
spring.cloud.openfeign.client.config.flight-service.loggerLevel=BASIC
spring.cloud.openfeign.client.config.flight-service.connectTimeout=5000
spring.cloud.openfeign.client.config.flight-service.readTimeout=10000

logging.level.com.project.bookingservice.client.feign=DEBUG

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/booking_db
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET}
# Flight Service URL (for RestClient)
flight-service.url=http://localhost:7172

# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

spring.data.web.pageable.max-page-size=100

# Booking TTL in minutes
booking.ttl-minutes=30
